<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ExaTipoExamen', 'doctrine');

/**
 * BaseExaTipoExamen
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ete_id_tipo_examen
 * @property string $ete_nombre_examen
 * @property Doctrine_Collection $ExaExamen
 * 
 * @method integer             getEteIdTipoExamen()    Returns the current record's "ete_id_tipo_examen" value
 * @method string              getEteNombreExamen()    Returns the current record's "ete_nombre_examen" value
 * @method Doctrine_Collection getExaExamen()          Returns the current record's "ExaExamen" collection
 * @method ExaTipoExamen       setEteIdTipoExamen()    Sets the current record's "ete_id_tipo_examen" value
 * @method ExaTipoExamen       setEteNombreExamen()    Sets the current record's "ete_nombre_examen" value
 * @method ExaTipoExamen       setExaExamen()          Sets the current record's "ExaExamen" collection
 * 
 * @package    info_examen
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExaTipoExamen extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('exa_tipo_examen');
        $this->hasColumn('ete_id_tipo_examen', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('ete_nombre_examen', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 80,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ExaExamen', array(
             'local' => 'ete_id_tipo_examen',
             'foreign' => 'exa_id_tipo_examen'));
    }
}