<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ExaExamen', 'doctrine');

/**
 * BaseExaExamen
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $exa_id_examen
 * @property integer $exa_id_tipo_examen
 * @property string $exa_nombre_examen
 * @property string $exa_descrip_examen
 * @property string $exa_observacion
 * @property ExaTipoExamen $ExaTipoExamen
 * @property Doctrine_Collection $ExaTuboExamen
 * 
 * @method integer             getExaIdExamen()        Returns the current record's "exa_id_examen" value
 * @method integer             getExaIdTipoExamen()    Returns the current record's "exa_id_tipo_examen" value
 * @method string              getExaNombreExamen()    Returns the current record's "exa_nombre_examen" value
 * @method string              getExaDescripExamen()   Returns the current record's "exa_descrip_examen" value
 * @method string              getExaObservacion()     Returns the current record's "exa_observacion" value
 * @method ExaTipoExamen       getExaTipoExamen()      Returns the current record's "ExaTipoExamen" value
 * @method Doctrine_Collection getExaTuboExamen()      Returns the current record's "ExaTuboExamen" collection
 * @method ExaExamen           setExaIdExamen()        Sets the current record's "exa_id_examen" value
 * @method ExaExamen           setExaIdTipoExamen()    Sets the current record's "exa_id_tipo_examen" value
 * @method ExaExamen           setExaNombreExamen()    Sets the current record's "exa_nombre_examen" value
 * @method ExaExamen           setExaDescripExamen()   Sets the current record's "exa_descrip_examen" value
 * @method ExaExamen           setExaObservacion()     Sets the current record's "exa_observacion" value
 * @method ExaExamen           setExaTipoExamen()      Sets the current record's "ExaTipoExamen" value
 * @method ExaExamen           setExaTuboExamen()      Sets the current record's "ExaTuboExamen" collection
 * 
 * @package    info_examen
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExaExamen extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('exa_examen');
        $this->hasColumn('exa_id_examen', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('exa_id_tipo_examen', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('exa_nombre_examen', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 80,
             ));
        $this->hasColumn('exa_descrip_examen', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('exa_observacion', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ExaTipoExamen', array(
             'local' => 'exa_id_tipo_examen',
             'foreign' => 'ete_id_tipo_examen'));

        $this->hasMany('ExaTuboExamen', array(
             'local' => 'exa_id_examen',
             'foreign' => 'ett_id_examen'));
    }
}