<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ExaTuboExamen', 'doctrine');

/**
 * BaseExaTuboExamen
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ett_id
 * @property integer $ett_id_tubo
 * @property integer $ett_id_examen
 * @property ExaTubo $ExaTubo
 * @property ExaExamen $ExaExamen
 * 
 * @method integer       getEttId()         Returns the current record's "ett_id" value
 * @method integer       getEttIdTubo()     Returns the current record's "ett_id_tubo" value
 * @method integer       getEttIdExamen()   Returns the current record's "ett_id_examen" value
 * @method ExaTubo       getExaTubo()       Returns the current record's "ExaTubo" value
 * @method ExaExamen     getExaExamen()     Returns the current record's "ExaExamen" value
 * @method ExaTuboExamen setEttId()         Sets the current record's "ett_id" value
 * @method ExaTuboExamen setEttIdTubo()     Sets the current record's "ett_id_tubo" value
 * @method ExaTuboExamen setEttIdExamen()   Sets the current record's "ett_id_examen" value
 * @method ExaTuboExamen setExaTubo()       Sets the current record's "ExaTubo" value
 * @method ExaTuboExamen setExaExamen()     Sets the current record's "ExaExamen" value
 * 
 * @package    info_examen
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExaTuboExamen extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('exa_tubo_examen');
        $this->hasColumn('ett_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('ett_id_tubo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ett_id_examen', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ExaTubo', array(
             'local' => 'ett_id_tubo',
             'foreign' => 'ext_id_tubo'));

        $this->hasOne('ExaExamen', array(
             'local' => 'ett_id_examen',
             'foreign' => 'exa_id_examen'));
    }
}