<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/05/22 07:27:58

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=info_examen_lab',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
