<?php

/**
 * ExaExamenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExaExamenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExaExamenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExaExamen');
    }

    public function getExamen($nombre) {
    	$parnombre="%".$nombre."%";
     	$q = $this->createQuery('exa')
                ->select('exa.exa_id_examen as id,exa.exa_id_tipo_examen as tipo, exa.exa_nombre_examen as nombre,exa.exa_observacion as observacion')
                ->where('exa.exa_nombre_examen like ?', $parnombre)
                ->orderBy('exa.exa_nombre_examen asc');
        // 		var_dump($q->buildSqlQuery());

        return $q->execute(array(), Doctrine_Core::HYDRATE_SCALAR);
    }

}