<?php

/**
 * ExaExamen
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    info_examen
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ExaExamen extends BaseExaExamen
{
	public function __toString()
  {
    return $this->getExaNombreExamen();
  }

   public function getNombreTipoExamen()
  {
    return $this->getExaTipoExamen();
    
  }
}