<?php

/**
 * ExaTuboTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExaTuboTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExaTuboTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExaTubo');
    }
}