<?php

/**
 * ExaTipoExamenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExaTipoExamenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExaTipoExamenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExaTipoExamen');
    }
}