<?php

/**
 * ExaTuboExamen
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    info_examen
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ExaTuboExamen extends BaseExaTuboExamen
{
	public function getNombreExamen()
  {
    return $this->getExaExamen();
    
  }
   public function getNombreTubo()
  {
    return $this-> getExaTubo();
    
  }
}