<?php

/**
 * ExaTuboExamenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExaTuboExamenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExaTuboExamenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExaTuboExamen');
    }
}