<?php

/**
 * ExaUsuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExaUsuarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExaUsuarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExaUsuario');
    }
}