<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/05/22 08:26:58
sfConfig::add(array(
  'mod_exa_tubo_examen_enabled' => true,
  'mod_exa_tubo_examen_view_class' => 'sfPHP',
));
