<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/05/22 07:48:40
sfConfig::add(array(
  'mod_exa_tipo_examen_enabled' => true,
  'mod_exa_tipo_examen_view_class' => 'sfPHP',
));
